nome = input("Digite o seu nome: ")
print("Boa noite " + nome + "!")
x = float(input("Entre com o 1º valor: "))
y = float(input("Entre com o 2º valor: "))
print("A soma dos dois valores digitados é ", (x + y) )
print("Olá Mundo!")